name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
      - name: Prepare output
        run: |
          mkdir gh-pages
          mkdir gh-pages/ch02
          mkdir gh-pages/ch03
          mkdir gh-pages/ch04
      # ---------- chapter 2 ----------
      - name: Build ch02/App
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=App
          cp -R bin/html5/bin gh-pages/ch02/App
      - name: Build ch02/EventDemo
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=EventDemo
          cp -R bin/html5/bin gh-pages/ch02/EventDemo
      - name: Build ch02/FirstAnimation
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=FirstAnimation
          cp -R bin/html5/bin gh-pages/ch02/FirstAnimation
      - name: Build ch02/KeyboardEvents
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=KeyboardEvents
          cp -R bin/html5/bin gh-pages/ch02/KeyboardEvents
      - name: Build ch02/KeyCodes
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=KeyCodes
          cp -R bin/html5/bin gh-pages/ch02/KeyCodes
      - name: Build ch02/MouseEvents
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MouseEvents
          cp -R bin/html5/bin gh-pages/ch02/MouseEvents
      - name: Build ch02/MousePos
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MousePos
          cp -R bin/html5/bin gh-pages/ch02/MousePos
      - name: Build ch02/Reparenting
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Reparenting
          cp -R bin/html5/bin gh-pages/ch02/Reparenting
      # ---------- chapter 3 ----------
      - name: Build ch03/Bobbing
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Bobbing
      - name: Build ch03/Circle
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Circle
      - name: Build ch03/Distance
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Distance
      - name: Build ch03/MouseDistance
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MouseDistance
      - name: Build ch03/Oval
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Oval
      - name: Build ch03/Pulse
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Pulse
      - name: Build ch03/Random
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Random
      - name: Build ch03/RotateToMouse
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=RotateToMouse
      - name: Build ch03/Wave1
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Wave1
      - name: Build ch03/Wave2
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Wave2
      # ---------- chapter 4 ----------
      - name: Build ch04/AnimatedFilters
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=AnimatedFilters
      - name: Build ch04/CurveThroughPoint
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=CurveThroughPoint
      - name: Build ch04/DrawingApp
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=DrawingApp
      - name: Build ch04/DrawingCurves
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=DrawingCurves
      - name: Build ch04/EmbedAsset1
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=EmbedAsset1
      - name: Build ch04/EmbedAsset2
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=EmbedAsset2
      - name: Build ch04/Filters
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Filters
      - name: Build ch04/GradientFill
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=GradientFill
      - name: Build ch04/LoadAsset1
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=LoadAsset1
      - name: Build ch04/LoadAsset2
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=LoadAsset2
      - name: Build ch04/MultiCurves1
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiCurves1
      - name: Build ch04/MultiCurves2
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiCurves2
      - name: Build ch04/MultiCurves3
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiCurves3
      - name: Build ch04/MultiCurves3Filled
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiCurves3Filled
      - name: Build ch04/MultiFilters
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiFilters
      - name: Build ch04/SimpleBitmap
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=SimpleBitmap
      - name: Build ch04/SprayPaint
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=SprayPaint
      - name: Build ch04/TransformColor
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=TransformColor
      - name: Upload Site
        if: ${{ github.repository_owner == 'joshtynjala' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: gh-pages
