name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
      - name: Prepare output
        run: |
          mkdir gh-pages
          mkdir gh-pages/ch02
          mkdir gh-pages/ch03
          mkdir gh-pages/ch04
      # ---------- chapter 2 ----------
      - name: Build ch02/App
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=App
          cp -R bin/html5/bin ../gh-pages/ch02/App
      - name: Build ch02/EventDemo
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=EventDemo
          cp -R bin/html5/bin ../gh-pages/ch02/EventDemo
      - name: Build ch02/FirstAnimation
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=FirstAnimation
          cp -R bin/html5/bin ../gh-pages/ch02/FirstAnimation
      - name: Build ch02/KeyboardEvents
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=KeyboardEvents
          cp -R bin/html5/bin ../gh-pages/ch02/KeyboardEvents
      - name: Build ch02/KeyCodes
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=KeyCodes
          cp -R bin/html5/bin ../gh-pages/ch02/KeyCodes
      - name: Build ch02/MouseEvents
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MouseEvents
          cp -R bin/html5/bin ../gh-pages/ch02/MouseEvents
      - name: Build ch02/MousePos
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MousePos
          cp -R bin/html5/bin ../gh-pages/ch02/MousePos
      - name: Build ch02/Reparenting
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Reparenting
          cp -R bin/html5/bin ../gh-pages/ch02/Reparenting
      - name: Build ch02/Reparenting2
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Reparenting
          cp -R bin/html5/bin ../gh-pages/ch02/Reparenting2
      # ---------- chapter 3 ----------
      - name: Build ch03/Bobbing
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Bobbing
          cp -R bin/html5/bin ../gh-pages/ch03/Bobbing
      - name: Build ch03/Circle
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Circle
          cp -R bin/html5/bin ../gh-pages/ch03/Circle
      - name: Build ch03/Distance
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Distance
          cp -R bin/html5/bin ../gh-pages/ch03/Distance
      - name: Build ch03/MouseDistance
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MouseDistance
          cp -R bin/html5/bin ../gh-pages/ch03/MouseDistance
      - name: Build ch03/Oval
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Oval
          cp -R bin/html5/bin ../gh-pages/ch03/Oval
      - name: Build ch03/Pulse
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Pulse
          cp -R bin/html5/bin ../gh-pages/ch03/Pulse
      - name: Build ch03/Random
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Random
          cp -R bin/html5/bin ../gh-pages/ch03/Random
      - name: Build ch03/RotateToMouse
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=RotateToMouse
          cp -R bin/html5/bin ../gh-pages/ch03/RotateToMouse
      - name: Build ch03/Wave1
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Wave1
          cp -R bin/html5/bin ../gh-pages/ch03/Wave1
      - name: Build ch03/Wave2
        working-directory: ch03
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Wave2
          cp -R bin/html5/bin ../gh-pages/ch03/Wave2
      # ---------- chapter 4 ----------
      - name: Build ch04/AnimatedFilters
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=AnimatedFilters
          cp -R bin/html5/bin ../gh-pages/ch04/AnimatedFilters
      - name: Build ch04/CurveThroughPoint
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=CurveThroughPoint
          cp -R bin/html5/bin ../gh-pages/ch04/CurveThroughPoint
      - name: Build ch04/DrawingApp
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=DrawingApp
          cp -R bin/html5/bin ../gh-pages/ch04/DrawingApp
      - name: Build ch04/DrawingCurves
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=DrawingCurves
          cp -R bin/html5/bin ../gh-pages/ch04/DrawingCurves
      - name: Build ch04/EmbedAsset1
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=EmbedAsset1
          cp -R bin/html5/bin ../gh-pages/ch04/EmbedAsset1
      - name: Build ch04/EmbedAsset2
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=EmbedAsset2
          cp -R bin/html5/bin ../gh-pages/ch04/EmbedAsset2
      - name: Build ch04/Filters
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Filters
          cp -R bin/html5/bin ../gh-pages/ch04/Filters
      - name: Build ch04/GradientFill
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=GradientFill
          cp -R bin/html5/bin ../gh-pages/ch04/GradientFill
      - name: Build ch04/LoadAsset1
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=LoadAsset1
          cp -R bin/html5/bin ../gh-pages/ch04/LoadAsset1
      - name: Build ch04/LoadAsset2
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=LoadAsset2
          cp -R bin/html5/bin ../gh-pages/ch04/LoadAsset2
      - name: Build ch04/MultiCurves1
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiCurves1
          cp -R bin/html5/bin ../gh-pages/ch04/MultiCurves1
      - name: Build ch04/MultiCurves2
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiCurves2
          cp -R bin/html5/bin ../gh-pages/ch04/MultiCurves2
      - name: Build ch04/MultiCurves3
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiCurves3
          cp -R bin/html5/bin ../gh-pages/ch04/MultiCurves3
      - name: Build ch04/MultiCurves3Filled
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiCurves3Filled
          cp -R bin/html5/bin ../gh-pages/ch04/MultiCurves3Filled
      - name: Build ch04/MultiFilters
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiFilters
          cp -R bin/html5/bin ../gh-pages/ch04/MultiFilters
      - name: Build ch04/SimpleBitmap
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=SimpleBitmap
          cp -R bin/html5/bin ../gh-pages/ch04/SimpleBitmap
      - name: Build ch04/SprayPaint
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=SprayPaint
          cp -R bin/html5/bin ../gh-pages/ch04/SprayPaint
      - name: Build ch04/TransformColor
        working-directory: ch04
        run: |
          haxelib run openfl build html5 -final -clean --app-main=TransformColor
          cp -R bin/html5/bin ../gh-pages/ch04/TransformColor
      - name: Build ch05/Acceleration1
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Acceleration1
          cp -R bin/html5/bin ../gh-pages/ch05/Acceleration1
      - name: Build ch05/Acceleration2
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Acceleration2
          cp -R bin/html5/bin ../gh-pages/ch05/Acceleration2
      - name: Build ch05/Acceleration3
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Acceleration3
          cp -R bin/html5/bin ../gh-pages/ch05/Acceleration3
      - name: Build ch05/FollowMouse1
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=FollowMouse1
          cp -R bin/html5/bin ../gh-pages/ch05/FollowMouse1
      - name: Build ch05/FollowMouse2
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=FollowMouse2
          cp -R bin/html5/bin ../gh-pages/ch05/FollowMouse2
      - name: Build ch05/Gravity
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Gravity
          cp -R bin/html5/bin ../gh-pages/ch05/Gravity
      - name: Build ch05/RotationalVelocity
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=RotationalVelocity
          cp -R bin/html5/bin ../gh-pages/ch05/RotationalVelocity
      - name: Build ch05/ShipSim
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=ShipSim
          cp -R bin/html5/bin ../gh-pages/ch05/ShipSim
      - name: Build ch05/Velocity1
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Velocity1
          cp -R bin/html5/bin ../gh-pages/ch05/Velocity1
      - name: Build ch05/Velocity2
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Velocity2
          cp -R bin/html5/bin ../gh-pages/ch05/Velocity2
      - name: Build ch05/VelocityAngle
        working-directory: ch05
        run: |
          haxelib run openfl build html5 -final -clean --app-main=VelocityAngle
          cp -R bin/html5/bin ../gh-pages/ch05/VelocityAngle
      - name: Build ch06/Bouncing1
        working-directory: ch06
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Bouncing1
          cp -R bin/html5/bin ../gh-pages/ch06/Bouncing1
      - name: Build ch06/Bouncing2
        working-directory: ch06
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Bouncing2
          cp -R bin/html5/bin ../gh-pages/ch06/Bouncing2
      - name: Build ch06/Fountain
        working-directory: ch06
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Fountain
          cp -R bin/html5/bin ../gh-pages/ch06/Fountain
      - name: Build ch06/Friction1
        working-directory: ch06
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Friction1
          cp -R bin/html5/bin ../gh-pages/ch06/Friction1
      - name: Build ch06/Friction2
        working-directory: ch06
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Friction2
          cp -R bin/html5/bin ../gh-pages/ch06/Friction2
      - name: Build ch06/Removal
        working-directory: ch06
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Removal
          cp -R bin/html5/bin ../gh-pages/ch06/Removal
      - name: Build ch06/ShipSim2
        working-directory: ch06
        run: |
          haxelib run openfl build html5 -final -clean --app-main=ShipSim2
          cp -R bin/html5/bin ../gh-pages/ch06/ShipSim2
      - name: Build ch06/ShipSimFriction
        working-directory: ch06
        run: |
          haxelib run openfl build html5 -final -clean --app-main=ShipSimFriction
          cp -R bin/html5/bin ../gh-pages/ch06/ShipSimFriction
      - name: Build ch07/Drag
        working-directory: ch07
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Drag
          cp -R bin/html5/bin ../gh-pages/ch07/Drag
      - name: Build ch07/DragAndMove1
        working-directory: ch07
        run: |
          haxelib run openfl build html5 -final -clean --app-main=DragAndMove1
          cp -R bin/html5/bin ../gh-pages/ch07/DragAndMove1
      - name: Build ch07/DragAndMove2
        working-directory: ch07
        run: |
          haxelib run openfl build html5 -final -clean --app-main=DragAndMove2
          cp -R bin/html5/bin ../gh-pages/ch07/DragAndMove2
      - name: Build ch07/MouseEvents
        working-directory: ch07
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MouseEvents
          cp -R bin/html5/bin ../gh-pages/ch07/MouseEvents
      - name: Build ch07/MouseMoveDrag
        working-directory: ch07
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MouseMoveDrag
          cp -R bin/html5/bin ../gh-pages/ch07/MouseMoveDrag
      - name: Build ch07/Throwing
        working-directory: ch07
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Throwing
          cp -R bin/html5/bin ../gh-pages/ch07/Throwing
      - name: Build ch08/Chain
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Chain
          cp -R bin/html5/bin ../gh-pages/ch08/Chain
      - name: Build ch08/ChainArray
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=ChainArray
          cp -R bin/html5/bin ../gh-pages/ch08/ChainArray
      - name: Build ch08/DoubleSpring
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=DoubleSpring
          cp -R bin/html5/bin ../gh-pages/ch08/DoubleSpring
      - name: Build ch08/EaseToMouse
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=EaseToMouse
          cp -R bin/html5/bin ../gh-pages/ch08/EaseToMouse
      - name: Build ch08/Easing1
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Easing1
          cp -R bin/html5/bin ../gh-pages/ch08/Easing1
      - name: Build ch08/Easing2
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Easing2
          cp -R bin/html5/bin ../gh-pages/ch08/Easing2
      - name: Build ch08/EasingOff
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=EasingOff
          cp -R bin/html5/bin ../gh-pages/ch08/EasingOff
      - name: Build ch08/MultiSpring
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=MultiSpring
          cp -R bin/html5/bin ../gh-pages/ch08/MultiSpring
      - name: Build ch08/OffsetSpring
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=OffsetSpring
          cp -R bin/html5/bin ../gh-pages/ch08/OffsetSpring
      - name: Build ch08/Spring1
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Spring1
          cp -R bin/html5/bin ../gh-pages/ch08/Spring1
      - name: Build ch08/Spring2
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Spring2
          cp -R bin/html5/bin ../gh-pages/ch08/Spring2
      - name: Build ch08/Spring3
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Spring3
          cp -R bin/html5/bin ../gh-pages/ch08/Spring3
      - name: Build ch08/Spring4
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Spring4
          cp -R bin/html5/bin ../gh-pages/ch08/Spring4
      - name: Build ch08/Spring5
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Spring5
          cp -R bin/html5/bin ../gh-pages/ch08/Spring5
      - name: Build ch08/TripleSpring
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=TripleSpring
          cp -R bin/html5/bin ../gh-pages/ch08/TripleSpring
      - name: Build ch08/Twips
        working-directory: ch08
        run: |
          haxelib run openfl build html5 -final -clean --app-main=Twips
          cp -R bin/html5/bin ../gh-pages/ch08/Twips
      - name: Upload Site
        if: ${{ github.repository_owner == 'joshtynjala' && github.event_name != 'pull_request' && github.ref_name == 'main' }}
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: gh-pages
