name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Set up Haxelib dependencies
        run: |
          haxelib install lime --quiet
          haxelib install openfl --quiet
      - name: Build ch02/App
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final --app-main=App
      - name: Build ch02/EventDemo
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final --app-main=EventDemo
      - name: Build ch02/FirstAnimation
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final --app-main=FirstAnimation
      - name: Build ch02/KeyboardEvents
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final --app-main=KeyboardEvents
      - name: Build ch02/KeyCodes
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final --app-main=KeyCodes
      - name: Build ch02/MouseEvents
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final --app-main=MouseEvents
      - name: Build ch02/MousePos
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final --app-main=MousePos
      - name: Build ch02/Reparenting
        working-directory: ch02
        run: |
          haxelib run openfl build html5 -final --app-main=Reparenting
